### ISSUE TITLE
This is a technical issue that can be handled when the List of Terms is regenerated.

### ISSUE THREAD

**Issue by mswoodburn** [tdwg/ltc#61]
This is a technical issue that can be handled when the List of Terms is regenerated. 

We have been trying to update the RFC 2119 keywords statement to the most up-to-date version on all TDWG standards pages that use it. The appropriate text can be seen on the [DwC List of terms page, section 1.2](https://dwc.tdwg.org/list/#12-rfc-2119-key-words) (raw text available [here](https://raw.githubusercontent.com/tdwg/dwc/master/build/termlist-header.md)).

_Originally posted by @baskaufs in https://github.com/tdwg/ltc/discussions/27#discussioncomment-7910380_

**Comment by ben-norton** [comment]
Done
