### ISSUE TITLE
Another technical issue.

### ISSUE THREAD

**Issue by mswoodburn** [tdwg/ltc#62]
Another technical issue. 

I think that in order to support internationalization, we have tried to use "IRI" (Internationalized Resource Identifier) instead of "URI" (Uniform Resource Identifier). In reviewing DwC and AC documents, I can see that we have not been consistent about this. But given that this is a new standard, I would recommend that we use IRI consistently here (and try to update the other TDWG docs to do the same). 

For those not familiar with this issue, IRI is effectively a superset of URI (all URIs are IRIs) that allows for some use of non-Latin characters. We are not likely to use non-Latin characters in our IRIs, but to be consistent with use in other standards (e.g. W3C), we should use the currently preferred form, IRI.

_Originally posted by @baskaufs in https://github.com/tdwg/ltc/discussions/27#discussioncomment-7910499_

**Comment by ben-norton** [comment]
Just to clarify, should all instances of URI should be replaced with IRI? See https://tdwg.github.io/ltc/terms/index.html
I replaced URI with IRI in the properties, but URI is still used in the header.

**Comment by magpiedin** [comment]
Thanks Ben -- replacing all "URI" instances in the header as well as term Definitions, Notes, etc. was my understanding.

We also have one term with URI in its name -- [`ltc:resourceURI`](http://rs.tdwg.org/ltc/terms/resourceURI), which is a broad match to [`abcd:resourceURI`](https://abcd.tdwg.org/terms/#resourceURI).  

Renaming that to something like `ltc:resourceIRI` makes sense to me if needed.

@baskaufs could you clarify?

**Comment by ben-norton** [comment]
Thanks Kate, those are very different types of changes.

**Comment by baskaufs** [comment]
I think everywhere would be best. When we created the dwciri: terms, they were originally dwcuri: but we decided that "iri" was best.

**Comment by magpiedin** [comment]
Thanks both (slightly very different indeed :)

In the [uri-to-iri branch](https://github.com/tdwg/ltc/pull/64), I just replaced URI w/ IRI in most of the `source` files.
If that makes sense, are you able to rebuild the github.io `docs` files &/or `source/rs.tdwg.org` files from there? 

No worries if easier to blow away that branch -- all ears you recommend a different way.

**Comment by ben-norton** [comment]
Awesome. I've been working on stadocgen. The goal is to begin the process of generating new docs by copying the latest versions of everything in source/terms, source/terms/mapping, and the rs.tdwg.org namespaces.csv. Once copied over, the csv data is validated against a csv schema. If you changed the column names, the validation process should fail. I was actually hoping that something like this would popup.

**Comment by magpiedin** [comment]
Sweet -- the source/terms csv columns should be in tact/unchanged, but 🤞/many thanks for stadocgen.  

Would you like me to go ahead & merge that branch to main, or prefer to test things first?

**Comment by ben-norton** [comment]
We have a problem keeping columns consistent. is_required was dropped in the latest iteration. We need more robust workflows to prevent this from happening, which stadocgen should help facilitate. I'll circle back soon.

**Comment by magpiedin** [comment]
ah bummer -- Thanks, Ben.  

To check -- that wouldn't happen to be "tdwgutility_required", ~2nd to last column in [ltc.csv](https://github.com/tdwg/ltc/blob/main/source/terms/ltc.csv) & others?

**Comment by ben-norton** [comment]
Yep. Thats on me. I just discovered this. I change several column names during the transformation process.
 Download latest versions > Make select copies > Rename Columns > Update Values (Yes -> True)

**Comment by magpiedin** [comment]
No worries -- Thanks for hunting it down  
(& either way, agreed on needing a workflow or terms-schema-check to catch/prevent column changes if/when it does happen on the ltc- or other tdwg-standard-repo end)

**Comment by ben-norton** [comment]
The updates to the documentation pages just passed the last local test. It'll get them posted by the end of the day.

**Comment by ben-norton** [comment]
Boom.
https://tdwg.github.io/ltc/index.html
