### ISSUE TITLE
Add a page to the LtC docs to list required LtC Classes & Terms

### ISSUE THREAD

**Issue by magpiedin** [tdwg/ltc#66]
Add a page to https://tdwg.github.io/ltc (and/or wiki?) to list the required LtC classes & terms

- Required classes are those where `tdwgutility_required` = Yes in [ltc_categories.csv](https://github.com/tdwg/ltc/blob/main/source/terms/ltc_categories.csv)
- Required terms in a class are those where `tdwgutility_required` = Yes in [ltc_terms.csv](https://github.com/tdwg/ltc/blob/main/source/terms/ltc_terms.csv)

...e.g., Currently:

These are mandatory classes & their mandatory terms:
1. [LatimerCoreScheme](https://tdwg.github.io/ltc/terms/#LatimerCoreScheme) class
    - [`ltc:isDistinctObjects`](https://tdwg.github.io/ltc/terms/#LatimerCoreScheme_isDistinctObjects) term
    - [`ltc:schemeName`](https://tdwg.github.io/ltc/terms/#LatimerCoreScheme_schemeName) term

2. [ObjectGroup](https://tdwg.github.io/ltc/terms/#ObjectGroup_ObjectGroup) class
    - [`ltc:baseTypeOfObjectGroup`](https://tdwg.github.io/ltc/terms/#ObjectGroup_baseTypeOfObjectGroup) term
 
3. [RecordLevel](https://tdwg.github.io/ltc/terms/#RecordLevel) class
    - [`ltc:hasIdentifier`](https://tdwg.github.io/ltc/terms/#RecordLevel_hasIdentifier) term
    - [`dcterms:license`](https://tdwg.github.io/ltc/terms/#RecordLevel_license) term

Optional classes may also include terms which are only required if an LtC record uses that optional class.  Currently there are 10 optional classes with at least one required terms -- noted in the [filtered list from Ben](https://github.com/tdwg/ltc/files/13907098/ltc_required_fields_20240111.csv)

**Comment by magpiedin** [comment]
fyi - the terms listed in the ltc_required_fields...csv list look a bit different from what's in the current LtC terms list 

e.g. [`schema:streetAddress`](https://tdwg.github.io/ltc/terms/index.html#Address_streetAddress) is also **tdwgutility_required** = "Yes", so should also be required

Here's a list of terms from the current [ltc_terms_source.csv](https://github.com/tdwg/ltc/blob/d7c4ae9f82044f4edc81857966e7725e76be964a/source/terms/ltc_terms_source.csv) where:
  - **tdwgutility_required** = "Yes"
  - **rdf_type** = "http://www.w3.org/1999/02/22-rdf-syntax-ns#Property"


namespace | term_localName | label | tdwgutility_organizedInClass | tdwgutility_required
-- | -- | -- | -- | --
schema: | addressCountry | Address Country | Address | Yes
schema: | streetAddress | Street Address | Address | Yes
ltc: | status | Status | CollectionStatusHistory | Yes
ltc: | statusType | Status Type | CollectionStatusHistory | Yes
ltc: | contactDetailCategory | Contact Detail Category | ContactDetail | Yes
ltc: | contactDetailValue | Contact Detail Value | ContactDetail | Yes
ltc: | identifierType | Identifier Type | Identifier | Yes
ltc: | identifierValue | Identifier | Identifier | Yes
ltc: | isDistinctObjects | Is Distinct Objects | LatimerCoreScheme | Yes
ltc: | schemeName | Scheme Name | LatimerCoreScheme | Yes
ltc: | objectClassificationName | Object Classification Name | ObjectClassification | Yes
ltc: | baseTypeOfObjectGroup | Base Type Of Object Group | ObjectGroup | Yes
ltc: | organisationalUnitName | Organisational Unit Name | OrganisationalUnit | Yes
ltc: | organisationalUnitType | Organisational Unit Type | OrganisationalUnit | Yes
ltc: | hasIdentifier | Has Identifier | RecordLevel | Yes
dcterms: | license | License | RecordLevel | Yes
ltc: | relationshipOfResource | Relationship Of Resource | ResourceRelationship | Yes
dwc: | resourceID | Resource ID | ResourceRelationship | Yes
ltc: | isMandatoryMetric | Is Mandatory Metric | SchemeMeasurementOrFact | Yes
ltc: | isRepeatableMetric | Is Repeatable Metric | SchemeMeasurementOrFact | Yes
ltc: | schemeMeasurementType | Scheme Measurement Type | SchemeMeasurementOrFact | Yes
ltc: | isMandatoryTerm | Is Mandatory Term | SchemeTerm | Yes
ltc: | isRepeatableTerm | Is Repeatable Term | SchemeTerm | Yes
ltc: | termName | Term Name | SchemeTerm | Yes
ltc: | locationName | Location Name | StorageLocation | Yes

**Comment by ben-norton** [comment]
Done. Added to Quick Reference and Stadocgen https://tdwg.github.io/ltc/quick-reference/index.html

**Comment by ben-norton** [comment]
Done. Added to Quick Reference and Stadocgen https://tdwg.github.io/ltc/quick-reference/index.html

**Comment by magpiedin** [comment]
Many thanks Ben -- & really sorry if this is a pain/belated -- Is it possible to add a "Class required" column after the "[Term] Required' column?

These are the 3 mandatory classes (where `tdwgutility_required` = Yes in [ltc_categories.csv](https://github.com/tdwg/ltc/blob/main/source/terms/ltc_categories.csv)):
1. [LatimerCoreScheme](https://tdwg.github.io/ltc/terms/#LatimerCoreScheme) class
2. [ObjectGroup](https://tdwg.github.io/ltc/terms/#ObjectGroup_ObjectGroup) class 
3. [RecordLevel](https://tdwg.github.io/ltc/terms/#RecordLevel) class

All ears if anything helps

**Comment by ben-norton** [comment]
Sure.

**Comment by ben-norton** [comment]
Is it possible to add a "Class required" column after the "[Term] Required' column?

These are the 3 mandatory classes (where tdwgutility_required = Yes in [ltc_categories.csv](https://github.com/tdwg/ltc/blob/main/source/terms/ltc_categories.csv)):

    [LatimerCoreScheme](https://tdwg.github.io/ltc/terms/#LatimerCoreScheme) class
    [ObjectGroup](https://tdwg.github.io/ltc/terms/#ObjectGroup_ObjectGroup) class
    [RecordLevel](https://tdwg.github.io/ltc/terms/#RecordLevel) class

@magpiedin
