### ISSUE TITLE
LtC CITATION.cff still containing the wrong license

### ISSUE THREAD

**Issue by mtrekels** [tdwg/ltc#67]
### Submitter

@mtrekels

### Justification

The license of the repo is changed, but the CITATION.cff wasn't updated accordingly

### Wiki Section

Home

### Url

https://github.com/tdwg/ltc/blob/main/CITATION.cff

### Suggested Action

Improvement

### Description

Change the file

**Comment by jbstatgen** [comment]
Both CFFs: license changed to CC-BY-4.0

Homepage Github repository: corrected link for the proposed citation of the release to the io web presence (not the repository).
