### ISSUE TITLE
Set up DNS domain

### ISSUE THREAD

**Issue by MattBlissett** [tdwg/ltc#72]
For released or soon-to-be-released standards, we set up a subdomain, e.g. ltc.tdwg.org, to avoid needing github.io or similar in documents and citations.

Should the subdomain for this site be ltc.tdwg.org?

**Comment by baskaufs** [comment]
I believe that makes sense since they have been referring to the proposed standard as LtC.

**Comment by stanblum** [comment]
The status and next steps for the LtC are on the Exec meeting(s) agenda
tomorrow.  I expect they will approve going forward with this domain name
-- ltc.tdwg.org.  But let's wait for those meetings.

@Matthew Blissett ***@***.***>, you should get a "go" signal by
your Wednesday morning.

**Comment by stanblum** [comment]
Thanks, Matt!

Cheers,

-Stan
