### ISSUE TITLE
Borrowed vocabulary namespace IRIs

### ISSUE THREAD

**Issue by baskaufs** [tdwg/ltc#81]
In the draft LtC List of Terms document, [section 2](https://ltc.tdwg.org/terms/index.html#2-borrowed-vocabulary), the namespace IRI for Schema needs to be `https://schema.org/`. The namespace IRI for ABCD needs to be `http://rs.tdwg.org/abcd/terms/` to support term dereferencing when the ABCD terms are ratified and go live.

**Comment by magpiedin** [comment]
@ben-norton -- the markdown is fixed for this ([here](https://github.com/tdwg/ltc/blob/main/source/md/termlist-header.md)) & should be ready for `stadocgen`
