### ISSUE TITLE
Fragment identifiers/bookmarks in List of Terms document

### ISSUE THREAD

**Issue by baskaufs** [tdwg/ltc#82]
The form of the fragment identifiers in the current draft of the LtC List of Terms document is `section_localName`, e.g. `https://ltc.tdwg.org/terms/#ObjectGroup_hasEvent`. In order to support redirection from the `http://rs.tdwg.org/` permanent IRIs, the fragment identifier needs to either be in the form `namespaceAbbreviation_localName`, e.g. `https://ltc.tdwg.org/terms/#ltc_hasEvent` or `localName`, e.g. `https://ltc.tdwg.org/terms/#hasEvent` if local names are all unique within the document. Separators other than underscore are also supported as long as they are valid for use within fragment identifiers.

**Comment by ben-norton** [comment]
This will be integrated into the next published version of the documentation pages.
