### ISSUE TITLE
ltc:OrganisationalUnit appears multiple times in the List of Terms document

### ISSUE THREAD

**Issue by baskaufs** [tdwg/ltc#83]
I just happened to notice that ltc:OrganisationalUnit occurs four times in the body of the document. I did not check to see whether that was the case for any other terms.

**Comment by mpitblado** [comment]
This does also occur for other terms. Examples include `chronometricAgeUncertaintyInYears` and `contactDetailValue`

**Comment by rondlg** [comment]
@ben-norton @mswoodburn @magpiedin @essvee 

-- As we didn't meet today, I want to make sure this doesn't fall off the radar.

**Comment by ben-norton** [comment]
We plan to reorganize the terms page so that each term appears once on the page allowing URIs to resolve properly
