### ISSUE TITLE
Check author & files for rs.tdwg.org

### ISSUE THREAD

**Issue by magpiedin** [tdwg/ltc#84]
A draft-version of the YAML files @baskaufs needs for rs.tdwg.org are forked here:

https://github.com/magpiedin/rs.tdwg.org/tree/master/process/document_metadata_processing/ltc_doc_list 

Could we check that the info there looks correct?

- @jbstatgen -- in that directory, the [authors_configuration.yaml](https://github.com/magpiedin/rs.tdwg.org/blob/master/process/document_metadata_processing/ltc_doc_list/authors_configuration.yaml) file is based on the [CITATION_release.cff](https://github.com/tdwg/ltc/blob/main/CITATION_release.cff)  

- The other 'document_configuration.yaml' file seems good to go to me, but please edit if needed.  (Or yell if you need a repo-invite)

Thanks for sanity-checks.  I'll submit a pull request early next week if no objections

**Comment by jbstatgen** [comment]
The YAML file seems fine to me. It corresponds to https://github.com/tdwg/ltc/blob/main/CITATION_release.cff, (minus the TDWG entry). That's the list of contributors that should be used for the official TDWG release.

After adding two minor changes, I created a pull request - let me know if there is a step that I missed.

**Comment by jbstatgen** [comment]
[document_configuration.yaml](https://github.com/magpiedin/rs.tdwg.org/blob/master/process/document_metadata_processing/ltc_doc_list/document_configuration.yaml) seems to make sense, as far as I can tell.

**Comment by magpiedin** [comment]
Thanks @jbstatgen -- Looks good

**Comment by baskaufs** [comment]
@jbstatgen Did you create the pull request back to the original tdwg repository or to a fork of it. I'm not seeing any open pull requests at rs.tdwg.org: https://github.com/tdwg/rs.tdwg.org/pulls

**Comment by magpiedin** [comment]
@baskaufs -- That was here on our forked copy - https://github.com/magpiedin/rs.tdwg.org/pull/1

I'll make a pull request to the original in a bit (just giving other folks a chance to check, but will do asap if you need)

**Comment by baskaufs** [comment]
@magpiedin No rush. I just was wondering why I didn't get pinged at the original repo. Take you time.

**Comment by baskaufs** [comment]
These files did get merged into the rs.tdwg.org repo in May 8 via https://github.com/tdwg/rs.tdwg.org/pull/162 . So I think this can be closed. The one issue that I'm aware of is that the list of authors in the YAML file does not agree with the list in the draft List of Terms doc. So I think the script generating it will need to be modified to pull from the YAML file so that they agree. But that is a separate issue, so I'll create a new issue for that.

**Comment by baskaufs** [comment]
The issue I created is https://github.com/tdwg/ltc/issues/88
