### ISSUE TITLE
Fix use of "Term name" in LtC List of Terms document

### ISSUE THREAD

**Issue by baskaufs** [tdwg/ltc#85]
[Section 3.3.3.1 of the SDS](https://github.com/tdwg/vocab/blob/master/sds/documentation-specification.md#33-vocabulary-descriptions) defines a required term metadata element called "Term name". As defined, the term name "is composed of the local name part of the term IRI, with a prepended namespace abbreviation (QName)". This is how "Term name" is used consistently in all other TDWG vocabulary lists of terms (see [this comparison](https://github.com/tdwg/tag/blob/master/documents/metadata_field_names.csv)). However, the LtC List of terms gives only the term local name as the value of "Term name", and lists what the SDS defines as the term name as "Qualified Term". This should be changed to conform to the requirement of the SDS and be consistent with other lists of terms.

**Comment by mswoodburn** [comment]
Related to #82
