### ISSUE TITLE
Missing fields in the LtC List of Terms document

### ISSUE THREAD

**Issue by baskaufs** [tdwg/ltc#86]
[Section 3.3.3.1 of the SDS](https://github.com/tdwg/vocab/blob/master/sds/documentation-specification.md#33-vocabulary-descriptions) describes metadata fields that should or must be provided for each term. Several of these are currently missing from the LtC List of Terms:

- Term version IRI (REQUIRED)
- Modified (RECOMMENDED)
- Decision (RECOMMENDED)

The first two are related to the version date when the term was last modified. Give that LtC is a new vocabulary, the last modified date will be the same as the creation date (in this case the ratification date of 2024-02-28). The Term version IRI will be the Term IRI, concatenated with a dash, then the last modified date. (See http://rs.tdwg.org/dwc/terms/associatedMedia as an example).

Once @MattBlissett runs the script to build the CSV tables in the rs.tdwg.org repo, theses values can be retrieved from the `term_modified` column of the appropriate table for the termlist (i.e. namespace). Those tables will have the path

`https://raw.githubusercontent.com/tdwg/rs.tdwg.org/master/database/database.csv`

where `database` is a name assigned for that namespace. For example, the EXIF terms borrowed by Audiovisual Core have the database name `exif-for-ac`, with the table located at:

`https://raw.githubusercontent.com/tdwg/rs.tdwg.org/master/exif-for-ac/exif-for-ac.csv`

The assigned database names that will be used to create the folders when Matt runs the script are listed [here](https://github.com/tdwg/rs.tdwg.org/blob/master/process/ltc-revisions/ltc-2024-02-28/config.yaml) under "database" for each namespace. The termlists that are included within each vocabulary will be added here after he runs the script:

https://github.com/tdwg/rs.tdwg.org/blob/master/vocabularies/vocabularies-members.csv

and the database names associated with the termlists will be here:

https://github.com/tdwg/rs.tdwg.org/blob/master/term-lists/term-lists.csv in the `database` column. 

The table joining term names to the decisions that affected them is here:

https://github.com/tdwg/rs.tdwg.org/blob/master/decisions/decisions-links.csv

So the build script needs to go through this table and add a link to each decision that affected it. The IRI to be used for the link is formed by concatenating `https://github.com/tdwg/rs.tdwg.org/blob/master/decisions/decisions-links.csv` and the local name listed in the table.

You can see what this looks like for a DwC term that has been the subject of a lot of Decisions: http://rs.tdwg.org/dwc/terms/basisOfRecord .

**Comment by ben-norton** [comment]
@baskaufs 
document_modified = the last modification of that specific term?

**Comment by baskaufs** [comment]
It's `term_modified` from the appropriate list of terms CSV for that namespace. See the notes above for how to find it. Not every term in a List of Terms document will have been changed the last time the document was modified.

**Comment by ben-norton** [comment]
Fixed. The decision field will be applicable after the first annual review.
