### ISSUE TITLE
Exposure of "datatype" as an RDF property of LtC terms?

### ISSUE THREAD

**Issue by baskaufs** [tdwg/ltc#87]
When I was reviewing the [usage of vocabulary term metadata property names](https://github.com/tdwg/tag/blob/master/documents/metadata_field_names.csv), I noticed the field "Datatype" was given. However, it isn't included as a column in [the source metadata table for the terms](https://github.com/tdwg/rs.tdwg.org/blob/master/process/ltc-revisions/ltc-2024-02-28/ltc.csv). I guess that's OK, since that property isn't a thing in other vocabularies. But because it isn't included in the table, it won't get exposed as RDF. Exposing it could be possible, with `rdf:datatype` as an appropriate linking property, although the current practice is to include such things as layers on top of the basic "bag of terms" layer.

**Comment by ben-norton** [comment]
@baskaufs 
Datatypes are stored in a separate csv here: https://github.com/tdwg/ltc/blob/main/source/terms/ltc_datatypes.csv

**Comment by mswoodburn** [comment]
Hi @baskaufs - we included datatype in draft versions of the source metadata table, but then separated it out to a separate csv in order to conform to the current practice that you mention as being a separate layer on top of the terms. However, it'd be great to expose this as RDF. Is there method to do that, either by putting it back into the source metadata table (probably simpler for management) or by adapting the scripts that generate the RDF to incorporate the additional CSV?

**Comment by baskaufs** [comment]
I think this would be something that would be worth a look by the TAG. The SDS says in [Section 4.4.2.2](https://github.com/tdwg/vocab/blob/master/sds/documentation-specification.md#44-vocabularies-term-lists-and-terms) that this kind of information should be described in a separate ontology document (probably written using OWL with something like Protege) and that such a document could be imported with the "bag of terms" RDF in a triplestore to create an enhanced vocabulary.

However, this was envisioned as a theoretical way to allow people to engage in ontology building without restricting the use of the basic bag of terms by people for whom the extra restrictions were not helpful. It has never (yet) been done in practice. There may be some better way to achieve this for specifying datatypes.

I think the key thing to consider is whether there are legitimate cases where people might want to use the terms in ways that violate the datatype restrictions that you have specified. If there are never cases where this would be reasonable, then perhaps the specified datatypes should be included with the basic term metadata. The feeling in the past (based mostly on experience with Darwin Core) is that the "bag of terms" shoud be as unencumbered as possible to make them the most broadly usable. @tucotuco may have thoughts on this.

It seems like the place for ensuring that the datatype recommendations are being followed would be via a validator. If that were the case, then maybe just having the recommended datatypes in a separate CSV would be the best strategy.

Since there are a number of factors that should be considered, it probably would be the best to have some discussion on this as a cross-TDWG issue by the TAG.

**Comment by tucotuco** [comment]
> I think the key thing to consider is whether there are legitimate cases where people might want to use the terms in ways that violate the datatype restrictions that you have specified. If there are never cases where this would be reasonable, then perhaps the specified datatypes should be included with the basic term metadata. The feeling in the past (based mostly on experience with Darwin Core) is that the "bag of terms" shoud be as unencumbered as possible to make them the most broadly usable. @tucotuco may have thoughts on this.

The [Simple Darwin Core flexibility design principle](https://dwc.tdwg.org/simple/#4-what-makes-it-flexible) is meant to make the terms as reusable as possible. An extension of that principle is that constraints should be declared within a different layer, and for a defined set of purposes. A specific reason for not declaring constraints (including data types) was to promote data sharing first and foremost, with the understanding that even sharing "bad" data was good in that they would be exposed for improvement, both by tools and by other people who might have the resources to do so even if the data publisher did not.

**Comment by ben-norton** [comment]
@tucotuco Have we reached an inflection point where the broader policies can be tightened? It sounds like the existing practice is an accommodation to support a wider strategy of facilitating adoption. If that goal is achieved, then the accommodations are arguably no longer needed. If thats the case, can we begin to roll then back and adopt for more targeted policies to support data quality improvements?

**Comment by tucotuco** [comment]
In principle, yes. It might be a natural evolution from the impending [Biodiversity Data Quality standard](https://github.com/tdwg/bdq).

**Comment by jbstatgen** [comment]
Thank you for a good start into the day.

**Comment by ben-norton** [comment]
The current design was intentional. We agree that datatype does not belong in the RDF, but we do plan to post it in the documentation. We found that datatype helps end users to better understand the standard itself.
