### ISSUE TITLE
wrongly formatted date for at least two LtC versions

### ISSUE THREAD

**Issue by DavidFichtmueller** [tdwg/ltc#92]
### Submitter

David Fichtmueller (@DavidFichtmueller)

### Justification

the version dates are formatted inconsistently, which is confusing and does not adhere to the IS 8601 standard

### Wiki Section

Home

### Url

https://github.com/tdwg/ltc/wiki#version-history

### Suggested Action

Improvement

### Description

There are at least two wrongly formatted dates in the version history table of LtC. The date format implies ISO 8601, but for those cases it is obvious that they are written as YYYY-DD-MM. For the remaining three dates, I can not asses, if they are correct, as both parts are <= 12, but at least for version 0.1 a plausibility check implies that it is correct. 

### Current Text

"2024-28-02" for version 1.0
"2023-19-10" for version 0.3

### Replacement Text

"2024-02-28" for version 1.0
"2023-10-19" for version 0.3

### Additional Comments

relevant XKCD: https://xkcd.com/1179/

**Comment by magpiedin** [comment]
Thanks David -- The dates that are clearly wrong are now fixed to YYYY-MM-DD - https://github.com/tdwg/ltc/wiki#version-history
